@qtype @qtype_structuredsteps @qtype_structuredsteps_convert
Feature: Student attempts a converted Computation question with partial credit
  As a student
  In order to receive CXC-aligned partial credit on a converted Computation question
  I need long_multiplication and long_division converted questions to grade each step independently

  Background:
    Given the following "users" exist:
      | username |
      | teacher  |
      | student  |
    And the following "courses" exist:
      | fullname | shortname | category |
      | Course 1 | C1        | 0        |
    And the following "course enrolments" exist:
      | user    | course | role           |
      | teacher | C1     | editingteacher |
      | student | C1     | student        |
    And the following "activities" exist:
      | activity | name               | intro                                      | course | idnumber    | grade | navmethod |
      | quiz     | Computation Quiz 1 | Converted Computation question attempt test | C1     | compquiz1   | 3     | free      |

  @javascript
  Scenario: Student gets partial credit on a converted long_multiplication question
    # This question mirrors the structure generated by ddwtos_generator for a
    # 3-step Computation long_multiplication question (e.g. 10101 JG1 family).
    # Engine: long_multiplication; grading: field_sum; all steps computational.
    # Student answers step 1 correctly and leaves steps 2-3 wrong → 1/3 marks.
    When I am on the "Course 1" "core_question > course question bank" page logged in as teacher
    And I add a "Structured Steps" question filling the form with:
      | Question name | structuredsteps-convert-longmult-001                  |
      | Question text | Calculate: 53 × 26                                    |
      | Default mark  | 3                                                     |
      | Engine        | long_multiplication                                   |
      | Model JSON    | {"schema_version":"1.0","engine":"long_multiplication","engine_version":"1.0","params":{},"grading":{"mode":"field_sum"},"steps":[{"id":"step1","label":"Step 1: Multiply units column (53 \u00d7 6)","type":"computational","marks":1},{"id":"step2","label":"Step 2: Multiply tens column (53 \u00d7 20)","type":"computational","marks":1},{"id":"step3","label":"Step 3: Add partial products","type":"computational","marks":1}],"fields":[{"id":"f1","step_id":"step1","type":"numberbox","expected":"318","marks":1,"tolerance":0},{"id":"f2","step_id":"step2","type":"numberbox","expected":"1060","marks":1,"tolerance":0},{"id":"f3","step_id":"step3","type":"numberbox","expected":"1378","marks":1,"tolerance":0}]} |
    And quiz "Computation Quiz 1" contains the following questions:
      | question                              | page | maxmark |
      | structuredsteps-convert-longmult-001  | 1    | 3.0     |
    And I log out
    And I am on the "Computation Quiz 1" "mod_quiz > View" page logged in as "student"
    And I press "Attempt quiz"
    Then "//input[@data-ss-field-id='f1']" "xpath_element" should exist
    # Enter correct answer for step 1 only
    And I set the field with xpath "//input[@data-ss-field-id='f1']" to "318"
    And I set the field with xpath "//input[@data-ss-field-id='f2']" to "999"
    And I set the field with xpath "//input[@data-ss-field-id='f3']" to "999"
    And I press "Finish attempt ..."
    And I press "Submit all and finish"
    And I click on "Submit all and finish" "button" in the "Submit all your answers and finish?" "dialogue"
    # Partial credit: 1 step correct out of 3 = 1.00/3.00
    Then I should see "1.00 out of 3.00"

  @javascript
  Scenario: Student gets full marks on a converted long_multiplication question
    When I am on the "Course 1" "core_question > course question bank" page logged in as teacher
    And I add a "Structured Steps" question filling the form with:
      | Question name | structuredsteps-convert-longmult-002                  |
      | Question text | Calculate: 53 × 26 (full marks)                       |
      | Default mark  | 3                                                     |
      | Engine        | long_multiplication                                   |
      | Model JSON    | {"schema_version":"1.0","engine":"long_multiplication","engine_version":"1.0","params":{},"grading":{"mode":"field_sum"},"steps":[{"id":"step1","label":"Step 1: Multiply units column (53 \u00d7 6)","type":"computational","marks":1},{"id":"step2","label":"Step 2: Multiply tens column (53 \u00d7 20)","type":"computational","marks":1},{"id":"step3","label":"Step 3: Add partial products","type":"computational","marks":1}],"fields":[{"id":"f1","step_id":"step1","type":"numberbox","expected":"318","marks":1,"tolerance":0},{"id":"f2","step_id":"step2","type":"numberbox","expected":"1060","marks":1,"tolerance":0},{"id":"f3","step_id":"step3","type":"numberbox","expected":"1378","marks":1,"tolerance":0}]} |
    And quiz "Computation Quiz 1" contains the following questions:
      | question                              | page | maxmark |
      | structuredsteps-convert-longmult-002  | 1    | 3.0     |
    And I log out
    And I am on the "Computation Quiz 1" "mod_quiz > View" page logged in as "student"
    And I press "Attempt quiz"
    Then "//input[@data-ss-field-id='f1']" "xpath_element" should exist
    And I set the field with xpath "//input[@data-ss-field-id='f1']" to "318"
    And I set the field with xpath "//input[@data-ss-field-id='f2']" to "1060"
    And I set the field with xpath "//input[@data-ss-field-id='f3']" to "1378"
    And I press "Finish attempt ..."
    And I press "Submit all and finish"
    And I click on "Submit all and finish" "button" in the "Submit all your answers and finish?" "dialogue"
    Then I should see "3.00 out of 3.00"

  @javascript
  Scenario: Student gets partial credit on a converted long_division question
    # Mirrors a 3-field long_division converted question (e.g. 10207 JG1 family
    # after phantom-slot fix: 3 real steps, not 4).
    # Student answers steps 1 and 2 correctly, step 3 wrong → 2/3 marks.
    When I am on the "Course 1" "core_question > course question bank" page logged in as teacher
    And I add a "Structured Steps" question filling the form with:
      | Question name | structuredsteps-convert-longdiv-001                   |
      | Question text | Find 3/4 \u00f7 1/2                                   |
      | Default mark  | 3                                                     |
      | Engine        | long_division                                         |
      | Model JSON    | {"schema_version":"1.0","engine":"long_division","engine_version":"1.0","params":{},"grading":{"mode":"field_sum"},"steps":[{"id":"step1","label":"Step 1: Numerator","type":"computational","marks":1},{"id":"step2","label":"Step 2: Denominator","type":"computational","marks":1},{"id":"step3","label":"Step 3: Divide","type":"computational","marks":1}],"fields":[{"id":"f1","step_id":"step1","type":"numberbox","expected":"3","marks":1,"tolerance":0},{"id":"f2","step_id":"step2","type":"numberbox","expected":"2","marks":1,"tolerance":0},{"id":"f3","step_id":"step3","type":"numberbox","expected":"6","marks":1,"tolerance":0}]} |
    And quiz "Computation Quiz 1" contains the following questions:
      | question                              | page | maxmark |
      | structuredsteps-convert-longdiv-001   | 1    | 3.0     |
    And I log out
    And I am on the "Computation Quiz 1" "mod_quiz > View" page logged in as "student"
    And I press "Attempt quiz"
    Then "//input[@data-ss-field-id='f1']" "xpath_element" should exist
    # Steps 1 and 2 correct, step 3 wrong → 2/3 marks
    And I set the field with xpath "//input[@data-ss-field-id='f1']" to "3"
    And I set the field with xpath "//input[@data-ss-field-id='f2']" to "2"
    And I set the field with xpath "//input[@data-ss-field-id='f3']" to "99"
    And I press "Finish attempt ..."
    And I press "Submit all and finish"
    And I click on "Submit all and finish" "button" in the "Submit all your answers and finish?" "dialogue"
    Then I should see "2.00 out of 3.00"
